// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: taxonomy.proto

package example_proto_types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Classification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kingdom   string `protobuf:"bytes,1,opt,name=kingdom,proto3" json:"kingdom,omitempty"`
	Phylum    string `protobuf:"bytes,2,opt,name=phylum,proto3" json:"phylum,omitempty"`
	Class     string `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`
	Order     string `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	Suborder  string `protobuf:"bytes,5,opt,name=suborder,proto3" json:"suborder,omitempty"`
	Family    string `protobuf:"bytes,6,opt,name=family,proto3" json:"family,omitempty"`
	Subfamily string `protobuf:"bytes,7,opt,name=subfamily,proto3" json:"subfamily,omitempty"`
	Genus     string `protobuf:"bytes,8,opt,name=genus,proto3" json:"genus,omitempty"`
	Species   string `protobuf:"bytes,9,opt,name=species,proto3" json:"species,omitempty"`
}

func (x *Classification) Reset() {
	*x = Classification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taxonomy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Classification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Classification) ProtoMessage() {}

func (x *Classification) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Classification.ProtoReflect.Descriptor instead.
func (*Classification) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{0}
}

func (x *Classification) GetKingdom() string {
	if x != nil {
		return x.Kingdom
	}
	return ""
}

func (x *Classification) GetPhylum() string {
	if x != nil {
		return x.Phylum
	}
	return ""
}

func (x *Classification) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *Classification) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *Classification) GetSuborder() string {
	if x != nil {
		return x.Suborder
	}
	return ""
}

func (x *Classification) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *Classification) GetSubfamily() string {
	if x != nil {
		return x.Subfamily
	}
	return ""
}

func (x *Classification) GetGenus() string {
	if x != nil {
		return x.Genus
	}
	return ""
}

func (x *Classification) GetSpecies() string {
	if x != nil {
		return x.Species
	}
	return ""
}

var File_taxonomy_proto protoreflect.FileDescriptor

var file_taxonomy_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x74, 0x61, 0x78, 0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x74, 0x61, 0x78, 0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x22, 0xf0, 0x01, 0x0a, 0x0e, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x6b, 0x69, 0x6e, 0x67, 0x64, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6b, 0x69, 0x6e, 0x67, 0x64, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x68, 0x79, 0x6c, 0x75,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x68, 0x79, 0x6c, 0x75, 0x6d, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x75, 0x62, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x75, 0x62, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x61, 0x6d, 0x69, 0x6c,
	0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x75, 0x62, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x67, 0x65, 0x6e, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x65,
	0x6e, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x70, 0x65, 0x63, 0x69, 0x65, 0x73, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x70, 0x65, 0x63, 0x69, 0x65, 0x73, 0x42, 0x2b, 0x5a,
	0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x6e, 0x63, 0x6d,
	0x61, 0x67, 0x75, 0x69, 0x72, 0x65, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_taxonomy_proto_rawDescOnce sync.Once
	file_taxonomy_proto_rawDescData = file_taxonomy_proto_rawDesc
)

func file_taxonomy_proto_rawDescGZIP() []byte {
	file_taxonomy_proto_rawDescOnce.Do(func() {
		file_taxonomy_proto_rawDescData = protoimpl.X.CompressGZIP(file_taxonomy_proto_rawDescData)
	})
	return file_taxonomy_proto_rawDescData
}

var file_taxonomy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_taxonomy_proto_goTypes = []interface{}{
	(*Classification)(nil), // 0: taxonomy.Classification
}
var file_taxonomy_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_taxonomy_proto_init() }
func file_taxonomy_proto_init() {
	if File_taxonomy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_taxonomy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Classification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_taxonomy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_taxonomy_proto_goTypes,
		DependencyIndexes: file_taxonomy_proto_depIdxs,
		MessageInfos:      file_taxonomy_proto_msgTypes,
	}.Build()
	File_taxonomy_proto = out.File
	file_taxonomy_proto_rawDesc = nil
	file_taxonomy_proto_goTypes = nil
	file_taxonomy_proto_depIdxs = nil
}
